# Generated by Django 5.0.1 on 2025-12-17 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AddField(
            model_name="profile",
            name="allow_trainer_requests",
            field=models.BooleanField(
                default=True,
                help_text="Allow trainers to send connection requests (clients only)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=3
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="certifications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"name": "NASM-CPT", "issuer": "NASM", "year": 2020, "number": "12345"}]',
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Public email (if different from account email)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Public phone number (if different from account)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(default="USA", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Used to calculate age (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="education",
            field=models.TextField(
                blank=True, help_text="Degrees, relevant education, etc."
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="fitness_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-Binary"),
                    ("prefer_not_to_say", "Prefer Not to Say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Standard hourly rate in USD",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="injuries_limitations",
            field=models.TextField(
                blank=True,
                help_text="Any injuries, medical conditions, or physical limitations",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_handle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_accepting_clients",
            field=models.BooleanField(
                default=True, help_text="Currently accepting new clients"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured trainers appear at top of search results",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Auto-populated from address",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Auto-populated from address",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="max_clients",
            field=models.IntegerField(
                blank=True,
                default=20,
                help_text="Maximum number of active clients",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="offers_gym_sessions",
            field=models.BooleanField(
                default=True, help_text="Trains clients at a gym"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="offers_home_visits",
            field=models.BooleanField(
                default=False, help_text="Will travel to client's home/location"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="offers_in_person",
            field=models.BooleanField(
                default=True, help_text="Offers in-person training sessions"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="offers_virtual",
            field=models.BooleanField(
                default=False, help_text="Offers online/video training sessions"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="package_pricing",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"5_sessions": 250, "10_sessions": 450, "20_sessions": 850}',
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_gym_name",
            field=models.CharField(
                blank=True,
                help_text="Primary gym location (e.g., 'LA Fitness on Main St')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_trainer_gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_preference", "No Preference"),
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-Binary"),
                ],
                default="no_preference",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - Listed in marketplace"),
                    ("unlisted", "Unlisted - Accessible via direct link only"),
                    ("private", "Private - Not accessible"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="response_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                help_text="% of messages responded to within 24 hours",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="service_radius",
            field=models.IntegerField(
                blank=True,
                help_text="Miles willing to travel for in-person sessions",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_workout_stats_publicly",
            field=models.BooleanField(
                default=False, help_text="Show workout stats on public profile"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_active",
            field=models.BooleanField(
                default=False, help_text="Has active paid subscription"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("free_trial", "Free Trial (30 days)"),
                    ("basic", "Basic ($29/month)"),
                    ("premium", "Premium ($79/month)"),
                    ("enterprise", "Enterprise ($149/month)"),
                ],
                default="free_trial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_reviews",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_sessions_completed",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default_avatar.jpg",
                null=True,
                upload_to="avatars/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Tell us about yourself",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fitness_goals",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='["Build Muscle", "Lose Weight", "Increase Endurance"]',
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="specializations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='["Strength Training", "HIIT", "Weight Loss", "Sports Performance"]',
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="years_experience",
            field=models.IntegerField(
                blank=True, help_text="Years as a professional trainer", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["city", "state"], name="authenticat_city_7764c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["latitude", "longitude"], name="authenticat_latitud_6bbec1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_accepting_clients", "subscription_active"],
                name="authenticat_is_acce_2200c5_idx",
            ),
        ),
    ]
