# Generated by Django 5.0.1 on 2025-12-16 02:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="YouTube or demo video link", null=True
                    ),
                ),
                (
                    "muscle_groups",
                    models.JSONField(
                        default=list,
                        help_text='List of muscle groups: ["chest", "triceps", "shoulders"]',
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("barbell", "Barbell"),
                            ("dumbbell", "Dumbbell"),
                            ("machine", "Machine"),
                            ("bodyweight", "Bodyweight"),
                            ("cable", "Cable"),
                            ("kettlebell", "Kettlebell"),
                            ("medicine_ball", "Medicine Ball"),
                            ("pullup_bar", "Pull-up Bar"),
                            ("TRX", "Suspension Trainer (TRX)"),
                            ("resistance_band", "Resistance Band"),
                            ("treadmill", "Treadmill"),
                            ("rower", "Rower"),
                            ("plyo_box", "Plyometric Box"),
                            ("slam_ball", "Slam Ball"),
                            ("sled_prowler", "Sled/Prowler"),
                            ("stability_ball", "Stability Ball"),
                            ("foam_roller", "Foam Roller"),
                            ("other", "Other"),
                        ],
                        default="bodyweight",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(
                        default=False, help_text="Official library exercise"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Push Day', 'Leg Day', 'Full Body'",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Overall workout notes"),
                ),
                ("workout_date", models.DateField(default=django.utils.timezone.now)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Total workout duration in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "energy_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="How energetic did you feel? (1-5)",
                        null=True,
                    ),
                ),
                (
                    "difficulty_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="How hard was the workout? (1-5)",
                        null=True,
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False, help_text="Mark as favorite for quick access"
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False, help_text="Save as reusable template"
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this template (if is_template=True)",
                        max_length=200,
                    ),
                ),
                (
                    "is_shared_with_trainer",
                    models.BooleanField(
                        default=False,
                        help_text="Client has shared this workout with their trainer",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-workout_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pr_type",
                    models.CharField(
                        choices=[
                            ("max_weight", "Max Weight"),
                            ("max_reps", "Max Reps at Weight"),
                            ("max_volume", "Max Total Volume"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("reps", models.IntegerField(blank=True, null=True)),
                (
                    "volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("date_achieved", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_records",
                        to="workouts.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prs_achieved",
                        to="workouts.workoutlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_achieved"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Exercise order in workout"
                    ),
                ),
                (
                    "sets_data",
                    models.JSONField(
                        default=list,
                        help_text="List of set objects with reps, weight, RPE, etc.",
                    ),
                ),
                ("target_sets", models.IntegerField(blank=True, null=True)),
                (
                    "target_reps",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '8-12', 'AMRAP', '10'",
                        max_length=50,
                    ),
                ),
                (
                    "target_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "rest_seconds",
                    models.IntegerField(
                        default=90,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercise_logs",
                        to="workouts.exercise",
                    ),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_logs",
                        to="workouts.workoutlog",
                    ),
                ),
            ],
            options={
                "ordering": ["workout_log", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(fields=["name"], name="workouts_ex_name_5d1c33_idx"),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["equipment"], name="workouts_ex_equipme_727db8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(
                fields=["user", "-workout_date"], name="workouts_wo_user_id_ce6fc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(
                fields=["user", "is_favorite"], name="workouts_wo_user_id_48f35b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(
                fields=["user", "is_template"], name="workouts_wo_user_id_607126_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalrecord",
            index=models.Index(
                fields=["user", "exercise", "pr_type"],
                name="workouts_pe_user_id_82c9c9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personalrecord",
            unique_together={("user", "exercise", "pr_type")},
        ),
        migrations.AddIndex(
            model_name="exerciselog",
            index=models.Index(
                fields=["workout_log", "order"], name="workouts_ex_workout_2f1f4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exerciselog",
            index=models.Index(
                fields=["exercise"], name="workouts_ex_exercis_2b9873_idx"
            ),
        ),
    ]
